### ISSUE TITLE
User Management Dashboard

### ISSUE THREAD

**Issue by esacteksab** [ITenthusiasm/svelte-kit-supertokens#2]
I'm new to both Svelte and SuperTokens, but going through SuperToken's guide, there seems to be an expectation of a user management dashboard at /api/dashboard or /auth/dashboard. When I attempt to add `Dashboard.init()` to `RecipeList`, this doesn't appear to work as expected. 

Creating this issue to raise awareness but also general curiosity. I couldn't find in your amazing docs where this was captured, so it wasn't clear to me if it was expected that I create it. 

Thanks!

**Comment by ITenthusiasm** [comment]
Hey @esacteksab, thanks for opening this. Yeah when I wrote the SuperTokens examples for `SvelteKit` and `Remix`, I didn't have the local machine's user management dashboard in mind. (I'm also not sure if that was already a feature or not when I wrote this code. I have not used the local one myself, yet.)

Is this something you're intending to use in development or in production? I'm assuming development since you wouldn't want anyone on the internet to have access to your user management dashboard. Is that correct?

**Comment by esacteksab** [comment]
Thanks for the response. Right now, it's in development. It did strike me as strange that a user control panel for a SaaS product would be on the local app, but sometimes I figure it's best not to ask why.

What I was encountering specifically was that I was attempting to sign up a fake user on my local development system, and I would get a response "User already exists". But I hadn't created it, so I didn't know how/where it existed. So I was looking to the dashboard to 1) have the visibility into what did exist and 2) manage users (e.g. delete an existing user for testing purposes). 

Your response leads me to believe that for a production use-case, I wouldn't need this dashboard so I shouldn't worry about it.

**Comment by ITenthusiasm** [comment]
@esacteksab Sorry. Responding like a month later. lol. Busy life.

Yeah I'm not sure why you were experiencing that email issue. But some here are some possibilities:

## If your `SUPERTOKENS_CONNECTION_URI` points to `https://try.supertokens.com`
That is a public URL that pretty much _anyone_ can use to do their SuperTokens testing. So it's _very_ possible that someone else created an account with the email you were trying to work with. Although you can test the app quickly and easily with the `https://try.supertokens.com` URI, I don't recommend using it when you're trying to do more intentional testing. (You never know if you're working with a user _you_ created or a user _someone else_ created. You probably also don't want real emails being exposed to the public.)

I'd recommend creating your own personal space to test out SuperTokens. You can do this by [signing up](https://supertokens.com/auth) for your own URL where you can manage users. You can also [host the SuperTokens core yourself](https://supertokens.com/blog/connect-supertokens-to-database#running-supertokens-and-postgresql-without-docker).

## If your `SUPERTOKENS_CONNECTION_URI` points to the URL belonging the SuperTokens account you [created](https://supertokens.com/auth)
Then you probably don't need the Dashboard API. You should just be able to login to SuperTokens and manage your users there. (Be **very** careful with the credentials for your personal SuperTokens URI. And be sure not to mix prod user data and dev user data in the same place.)

## If your `SUPERTOKENS_CONNECTION_URI` points to your local [self-hosted instance of SuperTokens](https://supertokens.com/blog/connect-supertokens-to-database#running-supertokens-and-postgresql-without-docker)
Then the Dashboard API could be useful for the problem you were describing. However, I personally try to avoid relying on the middleware that SuperTokens provides. :sweat_smile: Their middleware is really helpful if it serves your exact use case. But once you start to wander outside of that, it can get inflexible pretty quickly. I've found that relying on the middleware typically makes it more difficult for me to integrate with these SSR frameworks (Svelte Kit, Remix, etc.) in production. So I usually craft my own solution.

If you need to see the users that exist in your self-hosted instance of SuperTokens, you can try searching through their docs to get insight on how to see all the users of your app. (If they have a Dashboard API, that pretty much guarantees that `supertokens-node` has functions that can be used to get the details of which users are registered with your app. Otherwise the Dashboard API would be difficult for the SuperTokens team to build.) Or you can play around with the database that you're using to manage your users (if you're feeling bold and dangerous). For instance, consider https://supertokens.com/docs/emailpassword/common-customizations/user-pagination.

Let me know if any of this helps. (Again, I know it's late so this may be outdated. Sorry. Haha.)

---

This Issue is really helpful! It's useful for me to be aware that there's a Dashboard API at all. However, I probably won't be re-creating a custom User Management Dashboard UI here. :sweat_smile: I don't think I would host something like that alongside my application unless that app was the only thing managing my users. And even then, I'd want the management to be tailored to the kind of app I was building. But I can't predict what that will look like for each individual person who uses this repo as a reference.

I might consider it in the future; but it's unlikely that I will handle this because I don't think creating something like that would be as beneficial for people. And it would take a considerable amount of time.

**Comment by ITenthusiasm** [comment]
@esacteksab If it's okay, I think I'll close this for now (given that it's been a little over a month since the last comment). If there are any other concerns, I'd be happy to reopen this.

**Comment by AdamTmHun** [comment]
Ping pong @ITenthusiasm, I came across your repo, and it helped me SO MUCH, thank you.
There is just one issue I ran into, and this is this one with the dashboard. I was looking for the online user management dashboard on my SuperTokens tenant account, but I could not find it. I might be dumb and blind, but I think it is discontinued and now they only do the user dashboards. Can you help with this one?
