### ISSUE TITLE
Use with thirdpartypasswordless

### ISSUE THREAD

**Issue by fredt34** [ITenthusiasm/svelte-kit-supertokens#4]
Hi,

You sample app worked flawlessly - Thanks! 

So I optimistically went ahead tinkering, created an account on SuperTokens, installed and imported said thirdpartypasswordless; but now it seems I'm stuck because routes/login/+page.svelte only provides email/password method, right ?

Before I dig further myself, with my quite low capabilities, do you have by chance more examples addressing this configuration? Or should I try try expanding on examples from SuperTokens themselves ?

Many thanks

Fred

**Comment by ITenthusiasm** [comment]
Hey Fred! Glad the example app worked for you! :smile:

Unfortunately, you would be correct in saying that this repository only provides examples for the email/password recipe. I'd love to add more examples, but I just haven't had the time to do so. So I don't have any that I can give you at the moment.

However, I tried to set things up so that it would be fairly easy to switch between different methods. Most (if not all) of what you would have to change would probably be `/src/lib/server/utils/supertokens/index.ts` file. Just alter the `signin`/`signup` methods (and the like) to use whatever authentication recipe that you want to use. As long as you keep the same contract of returning the user (when authentication succeeds) or returning the error (when authentication fails) everything should pretty much just work. The ideal is that developers only need to change code in one place.

Of course, you'll also need to setup your desired recipe in `/src/hooks.server.ts`.

**Comment by fredt34** [comment]
Hi,

Thanks for your prompt answer! I gonna try, let's hope ChatGPT can help me!

**Comment by paolodina** [comment]
@fredt34, if you're able to work something out and wouldn't mind sharing, that would be great :-] No problem otherwise.

**Comment by fredt34** [comment]
_IF_ ... I'll be glad to, l  @paolodina !

**Comment by ITenthusiasm** [comment]
Hey all. I'm finally starting to come back to this project to make some improvements. I just added an example for integrating the `Passwordless` recipe. For the most part, it was a straightforward process. The main effort was in understanding the SDK and using it correctly.

I'm intending to address the `ThirdParty` recipe soon. However, I can't make any promises on how quickly it'll be complete. (If it's as easy as the `Passwordless` recipe, it hopefully shouldn't take too long.)

Of course, if anyone else learns how to use the SDK first and opens a PR, that's also fine. :slightly_smiling_face: The SuperTokens team seems more than happy to answer questions about their SDKs in the Discord.

---

I know this is way late, so I don't know how much relevancy this issue still holds for you all, but I figured an update would still be helpful.

**Comment by ITenthusiasm** [comment]
Lord willing, `ThirdParty` should be completed within 2-4 weeks-ish.

**Comment by ITenthusiasm** [comment]
@fredt34 and @paolodina, I've finally added a `ThirdParty` authentication example to this repo -- both using Built-in Providers and Custom Providers. I hope this helps you and the others who have been longing for this feature. :sweat_smile:

If there are any other questions, let me know. (Please be sure to read the `README` first, though.)

**Comment by paolodina** [comment]
@ITenthusiasm 

Had a quick glance before diving in deeper, great work, appreciate the effort thanks!
